# /etc/config/network —— LAN 接口静态 IP（旁路由）
# 设备：升腾 C30 / OpenWrt(Kwrt)
# 旁路由 IP：192.168.31.190，网关/DNS 指向主路由 192.168.31.1

config interface 'lan'
        option type 'bridge'
        option proto 'static'
        option ipaddr '192.168.31.190'
        option netmask '255.255.255.0'
        option gateway '192.168.31.1'
        option dns '192.168.31.1'
        option ifname 'eth0'
